spring:
  application:
    name: SW-Metric-backend
  profiles:
    active:
      - db
  data:
    mongodb:
      uri: mongodb+srv://Techatham:password8888@swmetriccluster.iif1w.mongodb.net/SoftwareMetricShopStore?retryWrites=true&w=majority&appName=SWMetricCluster
